apiVersion: 1

datasources:
  - name: InfluxDB_k6
    uid: InfluxDB_k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    jsonData:
      httpMode: GET
    editable: true
    isDefault: true
