{
 "title": "Web Analytics Dashboard",
 "description": "Only works with a special preview version of the Loki data source",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/nginx/access.log\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (statuscode) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3}) \"[$__interval]))",
     "legendFormat": "HTTP Status: {{statuscode}}"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(({job=\"nginx_access_log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>5\\\\d{2}) \" )[$__interval])) / (sum(rate(({job=\"nginx_access_log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3})\" )[$__interval])) / 100)",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate(({job=\"nginx_access_log\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({job=\"nginx_access_log\"} |= \"Mozilla\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(50000, sum by (ipaddress) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"(?P<ipaddress>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\"[$__interval])))",
     "legendFormat": "{{ipaddress}}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" \\\\d{3} (?P<value>\\\\d+) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "Countries right now",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 9 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (country_code) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\" \\\"(?P<country_code>.*)\\\"\"[$__interval]))",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/access.log\"}"
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "95th percentile of Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (quantile_over_time(0.95,{filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" \\\\d{3} \\\\d+ \\\".*?\\\" \\\".*\\\" \\\".*?\\\" (?P<value>[-+]?[0-9]*\\\\.?[0-9]+)\"[$__interval]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "sum by(host) (max_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" \\\\d{3} \\\\d+ \\\".*?\\\" \\\".*\\\" \\\".*?\\\" (?P<value>[-+]?[0-9]*\\\\.?[0-9]+)\"[$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statuscode) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3}) \"[$__interval]))",
     "legendFormat": "HTTP Status {{statuscode}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<value>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, sum by (useragent) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])))",
     "legendFormat": "{{useragent}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "topk(5, sum by (refferer) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\"http.*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])))",
     "legendFormat": "{{refferer}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(5, sum by (ipaddress) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"(?P<ipaddress>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\"[$__interval])))",
     "legendFormat": "{{ipaddress}}"
    }
   ]
  },
  {
   "title": "Top Requested HTML Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "topk(5,sum by (path) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"[GET|POST] (?P<path>.*?\\\\.html) HTTP\"[$__interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}